#!/usr/bin/env python3
"""
generate_web_assets.py
======================
Regenerates all lib/Website/*.h embedded C arrays from html_source/.

Usage:
    python3 tools/generate_web_assets.py

Run this every time you modify files under html_source/ before building.
The GitHub Actions release workflow calls this automatically.

Output:
    lib/Website/HtmlIndex.h      — HTML_INDEX  (raw string literal)
    lib/Website/HtmlProbes.h     — HTML_PROBES (raw string literal)
    lib/Website/HtmlSettings.h   — HTML_SETTINGS (raw string literal)
    lib/Website/HtmlAbout.h      — HTML_ABOUT (raw string literal)
    lib/Website/AssetCss.h       — ASSET_CSS_DATA / ASSET_CSS_SIZE (gzip byte array)
                                   + #define ASSET_CSS_GZIP
    lib/Website/AssetJs.h        — ASSET_JS_DATA / ASSET_JS_SIZE  (gzip byte array)
                                   + #define ASSET_JS_GZIP

If html_source/{filename} does not exist the corresponding header is left
unchanged so partial builds remain possible.
"""

import gzip
import os
import sys
import textwrap

# Resolve paths relative to this script (project root / tools/)
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
ROOT        = os.path.dirname(SCRIPT_DIR)
HTML_SRC    = os.path.join(ROOT, "html_source")
WEBSITE_LIB = os.path.join(ROOT, "lib", "Website")

# ---------------------------------------------------------------------------
# HTML pages — embedded as raw C string literals (no compression needed;
# they're served once and are small relative to CSS/JS)
# ---------------------------------------------------------------------------
HTML_PAGES = [
    ("index.html",    "HtmlIndex.h",    "HTML_INDEX"),
    ("probes.html",   "HtmlProbes.h",   "HTML_PROBES"),
    ("settings.html", "HtmlSettings.h", "HTML_SETTINGS"),
    ("about.html",    "HtmlAbout.h",    "HTML_ABOUT"),
]

def write_html_header(src_file, dst_file, var_name):
    if not os.path.exists(src_file):
        print(f"  SKIP  {src_file} (not found)")
        return
    with open(src_file, "r", encoding="utf-8") as f:
        content = f.read()
    # Escape any )=====  sequences inside the HTML that would close the raw
    # literal prematurely (extremely unlikely, but defensive).
    if ")=====" in content:
        print(f"  WARN  {src_file} contains ')=====' — escaping with alternative delimiter")
        content = content.replace(")=====", ")====X")
    header = f'const char {var_name}[] = R"=====(\n{content}\n)=====";'
    with open(dst_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + "\n")
    size = os.path.getsize(src_file)
    print(f"  OK    {os.path.basename(dst_file):25s}  {size//1024:4d} KB  (raw)")

# ---------------------------------------------------------------------------
# CSS / JS assets — gzip-compressed, embedded as uint8_t arrays
# ---------------------------------------------------------------------------
ASSET_FILES = [
    ("custom-boostrap.min.css", "AssetCss.h", "ASSET_CSS"),
    ("bootstrap.min.js",        "AssetJs.h",  "ASSET_JS"),
]

def bytes_to_c_array(data: bytes, indent: int = 4) -> str:
    """Return a formatted hex dump suitable for a C uint8_t initialiser list."""
    cols   = 16
    lines  = []
    prefix = " " * indent
    for i in range(0, len(data), cols):
        chunk = data[i : i + cols]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(prefix + hex_str + ",")
    # Remove trailing comma on last line
    if lines:
        lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)

def write_asset_header(src_file, dst_file, var_name):
    if not os.path.exists(src_file):
        print(f"  SKIP  {src_file} (not found)")
        return
    raw_size = os.path.getsize(src_file)
    with open(src_file, "rb") as f:
        raw_data = f.read()
    gz_data = gzip.compress(raw_data, compresslevel=9)
    gz_size = len(gz_data)
    saving  = (1.0 - gz_size / raw_size) * 100 if raw_size else 0

    array_body = bytes_to_c_array(gz_data)
    header = textwrap.dedent(f"""\
        // Auto-generated by tools/generate_web_assets.py — DO NOT EDIT MANUALLY
        // Source: {os.path.basename(src_file)}  ({raw_size} bytes raw → {gz_size} bytes gzip, -{saving:.0f}%)
        #pragma once
        #define {var_name}_GZIP 1
        static const uint8_t {var_name}_DATA[] PROGMEM = {{
        {array_body}
        }};
        static const size_t  {var_name}_SIZE = {gz_size};
    """)
    with open(dst_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    print(f"  OK    {os.path.basename(dst_file):25s}  {raw_size//1024:4d} KB → {gz_size//1024:4d} KB  (-{saving:.0f}%)")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    os.makedirs(WEBSITE_LIB, exist_ok=True)

    print("Generating HTML page headers …")
    for src_name, dst_name, var in HTML_PAGES:
        write_html_header(
            os.path.join(HTML_SRC, src_name),
            os.path.join(WEBSITE_LIB, dst_name),
            var,
        )

    print("\nGenerating gzip asset headers …")
    for src_name, dst_name, var in ASSET_FILES:
        write_asset_header(
            os.path.join(HTML_SRC, src_name),
            os.path.join(WEBSITE_LIB, dst_name),
            var,
        )

    print("\nDone. Rebuild firmware with: pio run")

if __name__ == "__main__":
    main()
